### ISSUE TITLE
Fix current bugs found

### ISSUE THREAD

**Issue by Clauvin** [Clauvin/Puzzle-Game#20]
So... yeah, expectable.

- [x] Reposition Adjacent Block does not spend any Stamina. (#21)
- [x] Stamina can be endlessly accumulated. (#22)
- [x] Skill can't be used even if there are adjacent blocks to be moved around. (#23)
- [x] More than one block in the same tile. (#24)
- [x] Hard limit of 4 squares walked by turn - it should be defined by Stamina. (#27)
- [x] Reposition Adjacent Block is highlighting the tile where the player is. (#28)
